### ISSUE TITLE
For Mongo Completed project, index.html does not render because it is misnamed

### ISSUE THREAD

**Issue by dfenjves** [upperlinecode/flask-and-MongoDB#1]
(for Jeffery Branch) References an index.html file to render in the index() method, but the file is called events.html. It all works fine if you either rename events.html to index.html, or update the rendering to point to events.html

**Comment by jeffreylancaster** [comment]
Fixed! I'm going to go in and update that routes-complete.py file tomorrow (with the new database info, etc.), but good catch!
